[project]
name = "infosearch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "nltk>=3.9.1",
    "pandas>=2.3.0",
    "pymorphy3>=2.0.4",
    "requests>=2.32.3",
]
